---
all:
  hosts:
    localhost:
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
  children:
    windows:
      children:
        hosts:
          sp1-infcon1.fbinsmi.com: