---
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_kerberos_delegation: true
ansible_winrm_server_cert_validation: ignore
ansible_user: ansible
ansible_password: Titl@pn!