name: Commit Message Check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - develop

jobs:
  commit-message-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check Commit Messages
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(feat|fix|docs|chore|style|refactor|perf|test)(\((.*)\))?:(.*)$'
          error: 'Your commit message does not follow the required format of <type>(<scope>): <subject>'
          flags: 'gim'
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true