name: semantic-release

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bump-release-version:
    # Only run this job if the triggering workflow was successful
    runs-on: self-hosted  # You can choose any available runner, but most Node.js projects work well on Linux.
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenanced

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"  # Use whatever version is required by your project.
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run semantic-release
      run: npx semantic-release
      env:
        #GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
